# Data loading

FREE DATA FROM WORLD BANK VIA GAPMINDER.ORG https://www.gapminder.org/data/

In [1]:
import pandas as pd

In [2]:
PATH_DATA = 'Data/gapminder.xlsx' #this assumes the file is in a directory called data
#PATH_DATA = 'gapminder.xlsx' #you can uncomment this if you've just stored the file in the same folder as the notebook

#Why are these in all caps
COL_YEAR = 'year'
COL_LIFE = 'lifeExp'
COL_POP = 'pop'
COL_GDP = 'gdpPercap'

In [3]:
#let's read in the data
pd.read_csv(PATH_DATA)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

In [5]:
#hmmm that didn't work, let's try again
df = pd.read_excel(PATH_DATA)

In [6]:
#look at first 5 rows
#ALWAYS DO THIS - don't trust the data read in correctly
df.head(5)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [7]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [ ]:
#I would like for year and population to be ints
df['year'] = #fill in

In [ ]:
df['pop'] = #fill in

In [8]:
#another option to do this in one step
#this is filled in so that if you don't get the above typed in, you can still move forward
#another option to do this in one step
df = pd.read_excel(PATH_DATA, dtype = {'year':int, 'pop':int})

# Some operations you should be familiar with

In [9]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [10]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [11]:
#Common operations like min, max, mean
df.mean()

year         1.979500e+03
lifeExp      5.947444e+01
pop          2.960121e+07
gdpPercap    7.215327e+03
dtype: float64

In [12]:
df['pop'].std()

106157896.7439147

### Subsetting - NOT having the code filled in above does not affect the cells below

In [13]:
df.head(5)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [14]:
#make a data frame that contains only country and life expectancy
df2 = df[['country','lifeExp']]

In [15]:
df2.head(5)

       country  lifeExp
0  Afghanistan   28.801
1  Afghanistan   30.332
2  Afghanistan   31.997
3  Afghanistan   34.020
4  Afghanistan   36.088

In [16]:
#make a data frame that contains all columns BUT continent
df3 = df.drop(columns = ['continent'])

In [17]:
df3.head(5)

       country  year  lifeExp       pop   gdpPercap
0  Afghanistan  1952   28.801   8425333  779.445314
1  Afghanistan  1957   30.332   9240934  820.853030
2  Afghanistan  1962   31.997  10267083  853.100710
3  Afghanistan  1967   34.020  11537966  836.197138
4  Afghanistan  1972   36.088  13079460  739.981106

In [19]:
#make a data frame that contains only observations after 1960 from the Americas
idx = (df['year'] >= 1960) & (df['continent'] == 'Americas') #this actually doesn't work! Why?
amer = df.loc[idx]

In [20]:
amer.head(5)

      country continent  year  lifeExp       pop     gdpPercap
50  Argentina  Americas  1962   65.142  21283783   7133.166023
51  Argentina  Americas  1967   65.634  22934225   8052.953021
52  Argentina  Americas  1972   67.065  24779799   9443.038526
53  Argentina  Americas  1977   68.481  26983828  10079.026740
54  Argentina  Americas  1982   69.942  29341374   8997.897412

In [27]:
#what was the mean life expectancy for countries in the Americas in 1972?
idx = (df['year'] == 1972)& (df['continent'] == 'Americas')
amer_1972 = df.loc[idx].reset_index(drop = True)
#find the mean here
amer_1972['lifeExp'].mean()

62.39492000000001

### Finding unique values and frequencies - NOT having the code filled in above does not affect the cells below

In [29]:
#How many unique values are there for continent?
print(df['continent'].nunique())

5

In [30]:
#What are they?
print(df['continent'].unique())

['Asia' 'Europe' 'Africa' 'Americas' 'Oceania']

In [31]:
#How often does each occur?
print(df['continent'].value_counts())

Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: continent, dtype: int64

In [33]:
#How many countries had data recorded in 1972?
idx = df['year'] == 1972
data_1972 = df[idx]
data_1972['country'].nunique()
#find how many with one more line

142

In [35]:
#Which continent has the most entries in 1972?
data_1972['continent'].mode()

0    Africa
dtype: object

In [36]:
data_1972['continent'].value_counts()

Africa      52
Asia        33
Europe      30
Americas    25
Oceania      2
Name: continent, dtype: int64