# Data loading

FREE DATA FROM WORLD BANK VIA GAPMINDER.ORG https://www.gapminder.org/data/

In [1]:
import pandas as pd

In [2]:
PATH_DATA = 'Data/gapminder.xlsx' #this assumes the file is in a directory called data
#PATH_DATA = 'gapminder.xlsx' #you can uncomment this if you've just stored the file in the same folder as the notebook

#Why are these in all caps
COL_YEAR = 'year'
COL_LIFE = 'lifeExp'
COL_POP = 'pop'
COL_GDP = 'gdpPercap'

In [3]:
df = pd.read_excel(PATH_DATA, dtype = {'year':int,'popn':int})

## Using apply

In [4]:
df.apply(len, axis = 0)

country      1704
continent    1704
year         1704
lifeExp      1704
pop          1704
gdpPercap    1704
dtype: int64

In [5]:
df.apply(len, axis = 1)

0       6
1       6
2       6
3       6
4       6
       ..
1699    6
1700    6
1701    6
1702    6
1703    6
Length: 1704, dtype: int64

In [6]:
df['lifeExp'].apply(round)

0       29
1       30
2       32
3       34
4       36
        ..
1699    62
1700    60
1701    47
1702    40
1703    43
Name: lifeExp, Length: 1704, dtype: int64

In [7]:
df.apply(round) #Why won't it work?

TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method

In [8]:
df.head(2)

       country continent  year  lifeExp      pop   gdpPercap
0  Afghanistan      Asia  1952   28.801  8425333  779.445314
1  Afghanistan      Asia  1957   30.332  9240934  820.853030

In [9]:
def pop_category(population: int)->str:
    '''
    Classify the population into a category based on value
    '''
    if pd.notnull(population):
        if population < 10000000:
            return 'Low'
        elif population < 100000000:
            return 'Medium'
        elif population < 1000000000:
            return 'High'
        else:
            return 'Mega'

In [10]:
help(pop_category)

Help on function pop_category in module __main__:

pop_category(population: int) -> str
    Classify the population into a category based on value

In [ ]:
pop_category.__doc__

In [ ]:
pop_category.__annotations__

In [12]:
cat = df['pop'].apply(pop_category)
cat.head(5)

0       Low
1       Low
2    Medium
3    Medium
4    Medium
Name: pop, dtype: object

In [13]:
df['pop_category'] = cat
df['pop_category'].value_counts()

Low       1045
Medium     582
High        69
Mega         8
Name: pop_category, dtype: int64

In [14]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap pop_category
0  Afghanistan      Asia  1952   28.801   8425333  779.445314          Low
1  Afghanistan      Asia  1957   30.332   9240934  820.853030          Low
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       Medium
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       Medium
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       Medium

In [15]:
def max_min(x):
    return max(x) - min(x) #max(28.801) - min(28.801)

In [17]:
df.apply(max_min)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [16]:
df2 = df[['lifeExp', 'pop']]
df2.apply(max_min) #this is axis = 0

lifeExp    5.900400e+01
pop        1.318623e+09
dtype: float64

In [19]:
df['lifeExp'].head(2)

0    28.801
1    30.332
Name: lifeExp, dtype: float64

In [18]:
df['lifeExp'].apply(max_min) #Why won't this work?

TypeError: 'float' object is not iterable

## Just FYI, not required and we may not cover it

In [ ]:
def century(int:x)->str:
    century = str(x // 100 + 1)
    return century

In [ ]:
df['year'].apply(century)

In [ ]:
df['year'].apply(lambda x: str(x//100 + 1))

In [ ]:
(df['year']//100 + 1).astype(str)