# Assignment 2: Working with Normal Forms and Relational Algebra

For this assignment, note the following so that you receive credit for your work: 
  
- All of your final answers to the questions will be entered in this notebook - anywhere you see Blank 1 or Blank 2 etc indicates a space to fill in the answer to a question. **Answers embedded in code will not be graded** - ask if you do not know how to edit a markdown cell.
  
- All of your code used to answer the questions will be filled into this notebook. Make sure your code shows ALL of the necessary steps and is executable and clearly prints the outputs. You will upload the notebook to Blackboard as part of your assignment.
  
- Your code must relfect what was covered in class as well as your answers to questions. Both code and answers should be brief. **Overly verbose submissions and/or unnecesssarily complex submissions relying predominantly on structures not covered in class will not receive full credit and may receive no credit.**
  
- You are expected to have questions about the data and assignment - both clarifications and those related to your work. Be sure to post your clarification questions (don't reveal any answers) on Piazza so the entire class can benefit.

In [1]:
#run this so you can see all of the columns in the dfs
import pandas as pd
pd.set_option('display.max_columns', None)

While we have not formally set up a database and will not be querying, we will be treating our tables (relations) as though they exist in the context of a database. Bear that in mind as you complete the assignment.

In the last homework, we saw that there was an issue with the species table. This has been corrected for you - use the file `species_fixed.csv` for this assignment, NOT the file that was given to you for Homework 1.

# Question 1 (3 Points)

If you used any online resources or collaborated with anyone, enter that information here. Also, remember that you are required to be able to explain and defend all of your work should you be asked.

Be as detailed as possible:
- If you visited any websites, include the URL and a description of what you were trying to figure out.
- If you used an AI tool, copy & paste the entire conversation, or if you had many prompts, save them into a document and write the document to .pdf and upload it - just indicate in the question block that you uploaded a file. Acceptable AI usage includes asking for help debugging code that you have written yourself, and asking for explanations and clarification of concepts or specific code structures to help you understand. **Plugging the questions into AI wholesale and copying the answers is not permitted** - plus, you need to use your brain so that you develop critical thinking skills because literally everyone on the planet can plug stuff into a chatbot.
- If you worked with a classmate, indicate who - you are welcome to complete assignments as a group of up to 4 people and turn in a single assignment (or the same assignment) - just put a comment in Blackboard with your names 
- If you only used your class notes (or nothing at all), indicate that. Do not leave this question blank.

Answer here **[
    
    Websites Visited: GeeksforGeeks, W3Schools
    
    AI Usage: Used to turn relational algebra into LaTeX math for markup. 
    
    Teammates: Mia Cummings, Elena Xu, Charlotte Sellers
   
    Class Notes Usage: relational algebra, explode()
]**

## Question 2 (20 points)

Read in the data from the parks file to a data frame called `parks`. There is a problem with the parks table that prevents it from achieving any normal form.

Fill in code below to correct this problem using procedures we discussed in class (be very careful not to create a new issue in the process of fixing this one!), and also answer the following questions:

What was the issue in terms of rules for normal forms? **[The "State" column contains multiple states, which violates the atomic requirement to meet 1st Normal Form.]** 

What was the issue in terms of what the data looked like (be specific here about what you saw)? **["Park Code" and "Park Name" represents the same information, and both seemingly uniquely identify the relation, which is not allowed because by definition a relation can only have 1 primary key. So we tried to determine their relationship to see if one column determines the other, and we concluded that the Park Code could be derived from Park Name, making Park Name determine Park Code.]**  

What is the key for the corrected table? **[Park Name, State]** 

Why is Park Name not sufficient for a (candidate/primary) key? **[Some Parks span several states, so to convert the relation into normal form, you would need to split up parks with multiple states into their own unique rows. After doing this, Park Name would not uniquely identify the relation, and would need State to be in a composite key.]**

In [2]:
#Fill in your code here
df = pd.read_csv('parks.csv')

In [3]:
print(df.shape)
df.nunique()

(56, 6)

Park Code    56
Park Name    56
State        27
Acres        55
Latitude     53
Longitude    55
dtype: int64

In [4]:
df

,Park Code,Park Name,State,Acres,Latitude,Longitude
0,ACAD,Acadia National Park,ME,47390,44.35,-68.21
1,ARCH,Arches National Park,UT,76519,38.68,-109.57
2,BADL,Badlands National Park,SD,242756,43.75,-102.50
3,BIBE,Big Bend National Park,TX,801163,29.25,-103.25
4,BISC,Biscayne National Park,FL,172924,25.65,-80.08
5,BLCA,Black Canyon of the Gunnison National Park,CO,32950,38.57,-107.72
6,BRCA,Bryce Canyon National Park,UT,35835,37.57,-112.18
7,CANY,Canyonlands National Park,UT,337598,38.20,-109.93
8,CARE,Capitol Reef National Park,UT,241904,38.20,-111.17
9,CAVE,Carlsbad Caverns National Park,NM,46766,32.17,-104.44
10,CHIS,Channel Islands National Park,CA,249561,34.01,-119.42
11,CONG,Congaree National Park,SC,26546,33.78,-80.78
12,CRLA,Crater Lake National Park,OR,183224,42.94,-122.10
13,CUVA,Cuyahoga Valley National Park,OH,32950,41.24,-81.55
14,DENA,Denali National Park and Preserve,AK,3372402,63.33,-150.50
15,DEVA,Death Valley National Park,"CA, NV",4740912,36.24,-116.82
16,DRTO,Dry Tortugas National Park,FL,64701,24.63,-82.87
17,EVER,Everglades National Park,FL,1508538,25.32,-80.93
18,GAAR,Gates Of The Arctic National Park and Preserve,AK,7523898,67.78,-153.30
19,GLAC,Glacier National Park,MT,1013572,48.80,-114.00
20,GLBA,Glacier Bay National Park and Preserve,AK,3224840,58.50,-137.00
21,GRBA,Great Basin National Park,NV,77180,38.98,-114.30
22,GRCA,Grand Canyon National Park,AZ,1217403,36.06,-112.14
23,GRSA,Great Sand Dunes National Park and Preserve,CO,42984,37.73,-105.51
24,GRSM,Great Smoky Mountains National Park,"TN, NC",521490,35.68,-83.53
25,GRTE,Grand Teton National Park,WY,309995,43.73,-110.80
26,GUMO,Guadalupe Mountains National Park,TX,86416,31.92,-104.87
27,HALE,Haleakala National Park,HI,29094,20.72,-156.17
28,HAVO,Hawaii Volcanoes National Park,HI,323431,19.38,-155.20
29,HOSP,Hot Springs National Park,AR,5550,34.51,-93.05
30,ISRO,Isle Royale National Park,MI,571790,48.10,-88.55
31,JOTR,Joshua Tree National Park,CA,789745,33.79,-115.90
32,KATM,Katmai National Park and Preserve,AK,3674530,58.50,-155.00
33,KEFJ,Kenai Fjords National Park,AK,669983,59.92,-149.65
34,KOVA,Kobuk Valley National Park,AK,1750717,67.55,-159.28
35,LACL,Lake Clark National Park and Preserve,AK,2619733,60.97,-153.42
36,LAVO,Lassen Volcanic National Park,CA,106372,40.49,-121.51
37,MACA,Mammoth Cave National Park,KY,52830,37.18,-86.10
38,MEVE,Mesa Verde National Park,CO,52122,37.18,-108.49
39,MORA,Mount Rainier National Park,WA,235625,46.85,-121.75
40,NOCA,North Cascades National Park,WA,504781,48.70,-121.20
41,OLYM,Olympic National Park,WA,922651,47.97,-123.50
42,PEFO,Petrified Forest National Park,AZ,93533,35.07,-109.78
43,PINN,Pinnacles National Park,CA,26606,36.48,-121.16
44,REDW,Redwood National Park,CA,112512,41.30,-124.00
45,ROMO,Rocky Mountain National Park,CO,265828,40.40,-105.58
46,SAGU,Saguaro National Park,AZ,91440,32.25,-110.50
47,SEKI,Sequoia and Kings Canyon National Parks,CA,865952,36.43,-118.68
48,SHEN,Shenandoah National Park,VA,199045,38.53,-78.35
49,THRO,Theodore Roosevelt National Park,ND,70447,46.97,-103.45
50,VOYA,Voyageurs National Park,MN,218200,48.50,-92.88
51,WICA,Wind Cave National Park,SD,28295,43.57,-103.48
52,WRST,Wrangell - St Elias National Park and Preserve,AK,8323148,61.00,-142.00
53,YELL,Yellowstone National Park,"WY, MT, ID",2219791,44.60,-110.50
54,YOSE,Yosemite National Park,CA,761266,37.83,-119.50
55,ZION,Zion National Park,UT,146598,37.30,-113.05

In [5]:
df['State'] = df['State'].str.split(', ')
parks = df.explode('State', ignore_index=True)
df2 = df[['Park Name', 'Park Code', 'Acres', 'Latitude', 'Longitude']]
df3 = df[['Park Name', 'State']]

parks

,Park Code,Park Name,State,Acres,Latitude,Longitude
0,ACAD,Acadia National Park,ME,47390,44.35,-68.21
1,ARCH,Arches National Park,UT,76519,38.68,-109.57
2,BADL,Badlands National Park,SD,242756,43.75,-102.50
3,BIBE,Big Bend National Park,TX,801163,29.25,-103.25
4,BISC,Biscayne National Park,FL,172924,25.65,-80.08
5,BLCA,Black Canyon of the Gunnison National Park,CO,32950,38.57,-107.72
6,BRCA,Bryce Canyon National Park,UT,35835,37.57,-112.18
7,CANY,Canyonlands National Park,UT,337598,38.20,-109.93
8,CARE,Capitol Reef National Park,UT,241904,38.20,-111.17
9,CAVE,Carlsbad Caverns National Park,NM,46766,32.17,-104.44
10,CHIS,Channel Islands National Park,CA,249561,34.01,-119.42
11,CONG,Congaree National Park,SC,26546,33.78,-80.78
12,CRLA,Crater Lake National Park,OR,183224,42.94,-122.10
13,CUVA,Cuyahoga Valley National Park,OH,32950,41.24,-81.55
14,DENA,Denali National Park and Preserve,AK,3372402,63.33,-150.50
15,DEVA,Death Valley National Park,CA,4740912,36.24,-116.82
16,DEVA,Death Valley National Park,NV,4740912,36.24,-116.82
17,DRTO,Dry Tortugas National Park,FL,64701,24.63,-82.87
18,EVER,Everglades National Park,FL,1508538,25.32,-80.93
19,GAAR,Gates Of The Arctic National Park and Preserve,AK,7523898,67.78,-153.30
20,GLAC,Glacier National Park,MT,1013572,48.80,-114.00
21,GLBA,Glacier Bay National Park and Preserve,AK,3224840,58.50,-137.00
22,GRBA,Great Basin National Park,NV,77180,38.98,-114.30
23,GRCA,Grand Canyon National Park,AZ,1217403,36.06,-112.14
24,GRSA,Great Sand Dunes National Park and Preserve,CO,42984,37.73,-105.51
25,GRSM,Great Smoky Mountains National Park,TN,521490,35.68,-83.53
26,GRSM,Great Smoky Mountains National Park,NC,521490,35.68,-83.53
27,GRTE,Grand Teton National Park,WY,309995,43.73,-110.80
28,GUMO,Guadalupe Mountains National Park,TX,86416,31.92,-104.87
29,HALE,Haleakala National Park,HI,29094,20.72,-156.17
30,HAVO,Hawaii Volcanoes National Park,HI,323431,19.38,-155.20
31,HOSP,Hot Springs National Park,AR,5550,34.51,-93.05
32,ISRO,Isle Royale National Park,MI,571790,48.10,-88.55
33,JOTR,Joshua Tree National Park,CA,789745,33.79,-115.90
34,KATM,Katmai National Park and Preserve,AK,3674530,58.50,-155.00
35,KEFJ,Kenai Fjords National Park,AK,669983,59.92,-149.65
36,KOVA,Kobuk Valley National Park,AK,1750717,67.55,-159.28
37,LACL,Lake Clark National Park and Preserve,AK,2619733,60.97,-153.42
38,LAVO,Lassen Volcanic National Park,CA,106372,40.49,-121.51
39,MACA,Mammoth Cave National Park,KY,52830,37.18,-86.10
40,MEVE,Mesa Verde National Park,CO,52122,37.18,-108.49
41,MORA,Mount Rainier National Park,WA,235625,46.85,-121.75
42,NOCA,North Cascades National Park,WA,504781,48.70,-121.20
43,OLYM,Olympic National Park,WA,922651,47.97,-123.50
44,PEFO,Petrified Forest National Park,AZ,93533,35.07,-109.78
45,PINN,Pinnacles National Park,CA,26606,36.48,-121.16
46,REDW,Redwood National Park,CA,112512,41.30,-124.00
47,ROMO,Rocky Mountain National Park,CO,265828,40.40,-105.58
48,SAGU,Saguaro National Park,AZ,91440,32.25,-110.50
49,SEKI,Sequoia and Kings Canyon National Parks,CA,865952,36.43,-118.68
50,SHEN,Shenandoah National Park,VA,199045,38.53,-78.35
51,THRO,Theodore Roosevelt National Park,ND,70447,46.97,-103.45
52,VOYA,Voyageurs National Park,MN,218200,48.50,-92.88
53,WICA,Wind Cave National Park,SD,28295,43.57,-103.48
54,WRST,Wrangell - St Elias National Park and Preserve,AK,8323148,61.00,-142.00
55,YELL,Yellowstone National Park,WY,2219791,44.60,-110.50
56,YELL,Yellowstone National Park,MT,2219791,44.60,-110.50
57,YELL,Yellowstone National Park,ID,2219791,44.60,-110.50
58,YOSE,Yosemite National Park,CA,761266,37.83,-119.50
59,ZION,Zion National Park,UT,146598,37.30,-113.05

In [6]:
# df #OG dataframe but in Normal Form (state is exploded into separate rows to have atomic values)
# df2 #Every column that partially depends on Composite Key (only Park Name, not State)
# df3 #Relation that only contains composite key that full determines every other column (lol theres no other columns)

## Question 3 (20 pts)

Read in the data from the species_fixed file. We will create a new table called taxonomy from the species table. This table will contain: Scientific Name, Family, Order, Category, and Common Name. You will end up with duplicate rows. Use the pandas function `drop_duplicates` to drop the duplicate rows:  
  
`taxonomy = taxonomy.drop_duplicates(subset = 'Scientific Name')`  

We are being specific about Scientific Name because some of the Common Name entries may differ due to the way the data was processed.

Include your code below for creating the taxonomy table.

Ignoring the Common Name processing weirdness, why did we end up with duplicates in the taxonomy table when we first made it even though there weren't duplicates in the species table? **"Species ID" serves as the primary key and uniquely identifies each row. Dropping this unique identifier in the taxonomy table omits the information needed to make each row unique, thus creating duplicates in the taxonomy table that weren't present in the species table.**  

After we drop the duplicates, there are **46022** unique species in the table (be sure to show the code you used to get this below).

In [7]:
#Creating Species Table
species = pd.read_csv('species_fixed.csv')
species
#Checking for dupes in OG Species Table
dupeS = species[species.duplicated(keep=False)]
dupeS

Empty DataFrame
Columns: [Unnamed: 0, Species ID, Park Name, Category, Order, Family, Scientific Name, Common Name, Record Status, Occurrence, Nativeness, Conservation Status]
Index: []

In [8]:
#Creating Taxonomy Table
taxonomy = species[['Scientific Name', 'Family', 'Order', 'Category', 'Common Name']]
taxonomy

#Checking for dupes in Taxonomy table
dupesT = taxonomy[taxonomy.duplicated(keep=False)]
dupesT

,Scientific Name,Family,Order,Category,Common Name
0,Alces alces,Cervidae,Artiodactyla,Mammal,Moose
2,Canis latrans,Canidae,Carnivora,Mammal,Coyote
5,Lynx canadensis,Felidae,Carnivora,Mammal,Canada Lynx
12,Mustela frenata,Mustelidae,Carnivora,Mammal,Long-Tailed Weasel
14,Mustela vison,Mustelidae,Carnivora,Mammal,American Mink
...,...,...,...,...,...
119243,Solanum triflorum,Solanaceae,Solanales,Vascular Plant,Cut-Leaf Nightshade
119244,Vitis arizonica,Vitaceae,Vitales,Vascular Plant,Canyon Grape
119245,Vitis vinifera,Vitaceae,Vitales,Vascular Plant,Wine Grape
119246,Larrea tridentata,Zygophyllaceae,Zygophyllales,Vascular Plant,Creosote Bush
119247,Tribulus terrestris,Zygophyllaceae,Zygophyllales,Vascular Plant,Puncture Vine

In [9]:
#Dropping Scientific Name Dupes
taxonomy = taxonomy.drop_duplicates(subset = 'Scientific Name')

#Checking if there are dupes left over after dropping
dupesTdropped = taxonomy[taxonomy.duplicated(keep=False)]
dupesTdropped

Empty DataFrame
Columns: [Scientific Name, Family, Order, Category, Common Name]
Index: []

In [14]:
print(taxonomy['Scientific Name'].nunique())

46022

## Question 4 (15 pts)

Now that you have created the taxonomy table, remove the columns that should be removed from the species table. Don't modify the new table, instead create a new table named `species_tab` with these columns removed. It must have this name to work with the code given below. Include the code below to do this.  

What is the primary key for the species table?  **[Species ID]**  

What is the primary key for the taxonomy table? **[Scientific Name]**  

Are there any foreign keys? List the foreign keys - say which table the key is in and which table and column it refers to. **[Scientific Name is the foreign key in the species table that serves as the primary key in the taxonomy table.]**

In [11]:
#fill in your code here
species_tab = species.drop(columns = ['Family', 'Order', 'Category', 'Common Name'])
species_tab

,Unnamed: 0,Species ID,Park Name,Scientific Name,Record Status,Occurrence,Nativeness,Conservation Status
0,0,ACAD-1000,Acadia National Park,Alces alces,Approved,Present,Native,NaN
1,1,ACAD-1001,Acadia National Park,Odocoileus virginianus,Approved,Present,Native,NaN
2,2,ACAD-1002,Acadia National Park,Canis latrans,Approved,Present,Not Native,Species of Concern
3,3,ACAD-1003,Acadia National Park,Canis lupus,Approved,Not Confirmed,Native,Endangered
4,4,ACAD-1004,Acadia National Park,Vulpes vulpes,Approved,Present,Unknown,NaN
...,...,...,...,...,...,...,...,...
119243,119243,ZION-2791,Zion National Park,Solanum triflorum,Approved,Present,Native,NaN
119244,119244,ZION-2792,Zion National Park,Vitis arizonica,Approved,Present,Native,NaN
119245,119245,ZION-2793,Zion National Park,Vitis vinifera,Approved,Present,Not Native,NaN
119246,119246,ZION-2794,Zion National Park,Larrea tridentata,Approved,Present,Native,NaN
119247,119247,ZION-2795,Zion National Park,Tribulus terrestris,Approved,Present,Not Native,NaN

## Question 5 (15 pts)

The pandas function `merge` in many ways mimics a SQL join, and we will use it for that purpose here. The purpose of a join is to combine data from two tables based on a common (or multiple common) attribute(s). To use `merge`:

 `pd.merge(df1,df2, on = shared_col_to_merge_on)`. 
 
There are actually some examples bundled with question 6. If the shared column between the two tables has a different name, we can use the arguments `left_on` and `right_on` to give the specific names for each table - the left table is the first one listed.  

Using the `merge` function and any other code needed, find the state with the most species considered endangered. Bear in mind that we don't want to double count the same species in the same state. 

The state is **[Blank_1]**

In [15]:
merged_1 = pd.merge(species_tab, parks, on = 'Park Name')
merged_1.head()

endangered = species_tab[species_tab['Conservation Status'] == 'Endangered']
print(endangered.shape)
endangered.head()

merged_2 = pd.merge(endangered, parks, on='Park Name')
print(merged_2.shape)
merged_2.head()
# merged_2[merged_2['Park Name'] == 'Death Valley National Park'] # tested for duplicates

state_counts = merged_2.groupby('State')['Scientific Name'].nunique()
state_counts

print(state_counts.sort_values(ascending=False).head())

(374, 8)
(415, 13)
State
HI    77
CA    69
NV    25
FL    24
AZ    16
Name: Scientific Name, dtype: int64

## Question 6 (this is a long one!) (27 pts)

We are interested in turtles found in parks in Virginia. We will look at 3 ways to isolate these species from the data. Then will think about the relational algebra and what would be the most efficient/optimal way. (And lol yes, we did just make it slightly more difficult by splitting out taxonomy but we will roll with it). We will consider Turtles as any species from the Order Testudines.

Here is one way to do this:

In [12]:
merged = pd.merge(taxonomy, species_tab, on = 'Scientific Name')
print(merged.shape)
merged2 = pd.merge(merged, parks, on = 'Park Name')
print(merged2.shape)
merged3 = merged2[(merged2['State']== 'VA')&(merged2['Order'] == 'Testudines')]
print(merged3.shape)
#we will get rid of those that were false reports
merged3[~merged3['Occurrence'].str.lower().str.contains('false')]

(119248, 12)
(138242, 17)
(9, 17)

,Scientific Name,Family,Order,Category,Common Name,Unnamed: 0,Species ID,Park Name,Record Status,Occurrence,Nativeness,Conservation Status,Park Code,State,Acres,Latitude,Longitude
12245,Chelydra serpentina,Chelydridae,Testudines,Reptile,Common Snapping Turtle,101294,SHEN-1360,Shenandoah National Park,Approved,Present,Native,NaN,SHEN,VA,199045,38.53,-78.35
12255,Chrysemys picta,Emydidae,Testudines,Reptile,Central Painted Turtle,101295,SHEN-1361,Shenandoah National Park,Approved,Present,Native,NaN,SHEN,VA,199045,38.53,-78.35
12268,Terrapene carolina,Emydidae,Testudines,Reptile,Box Turtle,101300,SHEN-1366,Shenandoah National Park,Approved,Present,Native,NaN,SHEN,VA,199045,38.53,-78.35
59790,Clemmys guttata,Emydidae,Testudines,Reptile,Spotted Turtle,101296,SHEN-1362,Shenandoah National Park,Approved,Present,Native,NaN,SHEN,VA,199045,38.53,-78.35

Write the relational algebra for the process above (it is fine to write the names of the operations as opposed to the symbols - you'll get to write the symbols on the quiz!). You can skip writing up the false reports step as that is identical in both processes we will look at. **$$
\sigma_{\text{State}='VA' \land \text{Order}='Testudines'}
\left(
(\text{taxonomy} \bowtie_{\text{Scientific Name}} \text{species\_tab})
\bowtie_{\text{Park Name}} \text{parks}
\right)
$$**

Here is a second way:

In [13]:
va = parks[parks['State'] == 'VA']
turtle = taxonomy[taxonomy['Order'] == 'Testudines']
merged1 = pd.merge(species_tab, va, on = 'Park Name')
print(merged1.shape)
merged2 = pd.merge(merged1, turtle, on = 'Scientific Name')
print(merged2.shape)
#we will get rid of those that were false reports
merged2 = merged2[~merged2['Occurrence'].str.lower().str.contains('false')]

va

(4655, 13)
(9, 17)

   Park Code                 Park Name State   Acres  Latitude  Longitude
50      SHEN  Shenandoah National Park    VA  199045     38.53     -78.35

Why can't we directly merge the table called va and the table called turtle? **[They don't have any columns in common.]**

Write the relational algebra for the process above (it is fine to write the names of the operations as opposed to the symbols - you'll get to write the symbols on the quiz!). You can skip writing up the false reports step as that is identical in both processes we will look at.

$$
\left(
\text{species\_tab}
\bowtie_{\text{Park Name}}
\sigma_{\text{State}='VA'}(\text{Parks})
\right)
\bowtie_{\text{Scientific Name}}
\sigma_{\text{Order}='Testudines'}(\text{taxonomy})
$$

These are equivalent (won't ask you to do the proof!). However, one method is more efficient than the other. Explain using information from the actual coded data what creates the differences in efficiency - remember this must be based on facts revealed by code. We are talking about efficiency as discussed in class...if your answer is something like fewer lines of code or a drawn out relational algebra proof talking about pushdowns, your answer is wrong. (HINT: notice the extra print lines added in, those should help you).  

The method that is more efficient is: **The second method.** 

It is more efficient because and based on: **The output of the .shape method that tells us how many rows and columns are in our merged data frames. The second method uses conditionals first to shrink the size of the data frames and then perform merge. The df's 'va' and 'turtle' are both reduced before they are joined together, whereas in the first option, the df's are merged first (creating large df's) and then reduced. The second method is much more efficient because it avoids large df's being stored in variables.**